---
abstract: 'a set of Perl::Critic policies implemented and used by logicLAB'
author:
  - 'Jonas B. Nielsen (jonasbn), <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.132830'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl-Critic-logicLAB
provides:
  Perl::Critic::logicLAB:
    file: lib/Perl/Critic/logicLAB.pm
    version: 0.08
requires:
  Perl::Critic::Policy::logicLAB::ProhibitShellDispatch: 0
  Perl::Critic::Policy::logicLAB::ProhibitUseLib: 0
  Perl::Critic::Policy::logicLAB::RequirePackageNamePattern: 0
  Perl::Critic::Policy::logicLAB::RequireSheBang: 0
  Perl::Critic::Policy::logicLAB::RequireVersionFormat: 0
  perl: v5.6.0
resources:
  ProjectChangelog: http://logiclab.jira.com/browse/PCLL#selectedTab=com.atlassian.jira.plugin.system.project%3Achangelog-panel
  ProjectSite: http://logicLAB.jira.com/browse/PCLL
  ProjectWiki: http://logiclab.jira.com/wiki/display/PCLL/Home
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Perl-Critic-logicLAB
  homepage: http://logiclab.jira.com/wiki/display/PCLL/Home
  license: http://www.perlfoundation.org/artistic_license_1_0
  repository: https://github.com/jonasbn/pcll
version: 0.08
